# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maingui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(873, 572)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("DemoLogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 871, 571))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.glViewer = QAntennaViewer(self.horizontalLayoutWidget)
        self.glViewer.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glViewer.sizePolicy().hasHeightForWidth())
        self.glViewer.setSizePolicy(sizePolicy)
        self.glViewer.setMinimumSize(QtCore.QSize(100, 100))
        self.glViewer.setMaximumSize(QtCore.QSize(900, 900))
        self.glViewer.setSizeIncrement(QtCore.QSize(1, 1))
        self.glViewer.setObjectName("glViewer")
        self.horizontalLayout.addWidget(self.glViewer)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.logoDisplay = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logoDisplay.sizePolicy().hasHeightForWidth())
        self.logoDisplay.setSizePolicy(sizePolicy)
        self.logoDisplay.setMaximumSize(QtCore.QSize(16777215, 111))
        self.logoDisplay.setText("")
        self.logoDisplay.setPixmap(QtGui.QPixmap("anokiwave_logo.png"))
        self.logoDisplay.setObjectName("logoDisplay")
        self.verticalLayout_2.addWidget(self.logoDisplay)
        self.groupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox.setMinimumSize(QtCore.QSize(200, 130))
        self.groupBox.setMaximumSize(QtCore.QSize(2000, 140))
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 161, 81))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.labelTheta = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelTheta.setObjectName("labelTheta")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelTheta)
        self.thetaBox = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.thetaBox.setMinimum(-360.0)
        self.thetaBox.setMaximum(360.0)
        self.thetaBox.setSingleStep(0.5)
        self.thetaBox.setObjectName("thetaBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.thetaBox)
        self.labelPhi = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelPhi.setObjectName("labelPhi")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelPhi)
        self.phiBox = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.phiBox.setMinimum(-360.0)
        self.phiBox.setMaximum(360.0)
        self.phiBox.setSingleStep(0.5)
        self.phiBox.setObjectName("phiBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.phiBox)
        self.labelWavelength = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelWavelength.setObjectName("labelWavelength")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelWavelength)
        self.waveLengthBox = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.waveLengthBox.setMinimumSize(QtCore.QSize(62, 0))
        self.waveLengthBox.setMinimum(26.5)
        self.waveLengthBox.setMaximum(30.0)
        self.waveLengthBox.setSingleStep(0.1)
        self.waveLengthBox.setProperty("value", 28.0)
        self.waveLengthBox.setObjectName("waveLengthBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.waveLengthBox)
        self.beamDefButton = QtWidgets.QPushButton(self.groupBox)
        self.beamDefButton.setGeometry(QtCore.QRect(10, 110, 161, 23))
        self.beamDefButton.setObjectName("beamDefButton")
        self.verticalLayout_2.addWidget(self.groupBox)
        self.txRxModeBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.txRxModeBox.setMaximumSize(QtCore.QSize(16777215, 40))
        self.txRxModeBox.setFlat(True)
        self.txRxModeBox.setObjectName("txRxModeBox")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.txRxModeBox)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 291, 21))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButtonTx = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioButtonTx.setChecked(True)
        self.radioButtonTx.setObjectName("radioButtonTx")
        self.horizontalLayout_2.addWidget(self.radioButtonTx)
        self.radioButtonRx = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioButtonRx.setObjectName("radioButtonRx")
        self.horizontalLayout_2.addWidget(self.radioButtonRx)
        self.verticalLayout_2.addWidget(self.txRxModeBox)
        self.curSettingsLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.curSettingsLabel.setEnabled(False)
        self.curSettingsLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.curSettingsLabel.setObjectName("curSettingsLabel")
        self.verticalLayout_2.addWidget(self.curSettingsLabel)
        self.programButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.programButton.setEnabled(False)
        self.programButton.setMinimumSize(QtCore.QSize(0, 50))
        self.programButton.setObjectName("programButton")
        self.verticalLayout_2.addWidget(self.programButton)
        self.spiStatusLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.spiStatusLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.spiStatusLabel.setStyleSheet("QLabel {color : red; }")
        self.spiStatusLabel.setTextFormat(QtCore.Qt.AutoText)
        self.spiStatusLabel.setObjectName("spiStatusLabel")
        self.verticalLayout_2.addWidget(self.spiStatusLabel)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "AWMF-0108 Demo Kit"))
        self.groupBox.setTitle(_translate("Dialog", "Beam Direction"))
        self.labelTheta.setText(_translate("Dialog", "theta"))
        self.labelPhi.setText(_translate("Dialog", "phi"))
        self.labelWavelength.setText(_translate("Dialog", "wavelength"))
        self.beamDefButton.setText(_translate("Dialog", "Calculate"))
        self.txRxModeBox.setTitle(_translate("Dialog", "Transmit/Receive Mode"))
        self.radioButtonTx.setText(_translate("Dialog", "Transmit"))
        self.radioButtonRx.setText(_translate("Dialog", "Receive"))
        self.curSettingsLabel.setText(_translate("Dialog", "(0,0, TX)"))
        self.programButton.setText(_translate("Dialog", "Program"))
        self.spiStatusLabel.setText(_translate("Dialog", "SPI Interposer not detected "))

from qantennaviewer import QAntennaViewer
