# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maingui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(873, 572)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("DemoLogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 871, 571))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.glViewer = QAntennaViewer(self.horizontalLayoutWidget)
        self.glViewer.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glViewer.sizePolicy().hasHeightForWidth())
        self.glViewer.setSizePolicy(sizePolicy)
        self.glViewer.setMinimumSize(QtCore.QSize(100, 100))
        self.glViewer.setMaximumSize(QtCore.QSize(900, 900))
        self.glViewer.setSizeIncrement(QtCore.QSize(1, 1))
        self.glViewer.setObjectName("glViewer")
        self.horizontalLayout.addWidget(self.glViewer)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.logoDisplay = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logoDisplay.sizePolicy().hasHeightForWidth())
        self.logoDisplay.setSizePolicy(sizePolicy)
        self.logoDisplay.setMaximumSize(QtCore.QSize(16777215, 111))
        self.logoDisplay.setToolTip("")
        self.logoDisplay.setText("")
        self.logoDisplay.setPixmap(QtGui.QPixmap("anokiwave_logo.png"))
        self.logoDisplay.setObjectName("logoDisplay")
        self.verticalLayout_2.addWidget(self.logoDisplay)
        self.groubBoxAntenna = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groubBoxAntenna.setMaximumSize(QtCore.QSize(16777215, 50))
        self.groubBoxAntenna.setObjectName("groubBoxAntenna")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.groubBoxAntenna)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 171, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radio4x1Button = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.radio4x1Button.setChecked(True)
        self.radio4x1Button.setObjectName("radio4x1Button")
        self.horizontalLayout_3.addWidget(self.radio4x1Button)
        self.radio2x2Button = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.radio2x2Button.setObjectName("radio2x2Button")
        self.horizontalLayout_3.addWidget(self.radio2x2Button)
        self.verticalLayout_2.addWidget(self.groubBoxAntenna)
        self.groupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox.setMinimumSize(QtCore.QSize(200, 130))
        self.groupBox.setMaximumSize(QtCore.QSize(2000, 220))
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 172, 111))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.labelTheta = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelTheta.setObjectName("labelTheta")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelTheta)
        self.thetaBox = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.thetaBox.setDecimals(0)
        self.thetaBox.setMinimum(-90.0)
        self.thetaBox.setMaximum(90.0)
        self.thetaBox.setSingleStep(1.0)
        self.thetaBox.setObjectName("thetaBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.thetaBox)
        self.labelPhi = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelPhi.setObjectName("labelPhi")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelPhi)
        self.phiBox = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.phiBox.setToolTipDuration(1)
        self.phiBox.setDecimals(0)
        self.phiBox.setMinimum(-360.0)
        self.phiBox.setMaximum(361.0)
        self.phiBox.setSingleStep(1.0)
        self.phiBox.setObjectName("phiBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.phiBox)
        self.labelWavelength = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelWavelength.setObjectName("labelWavelength")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelWavelength)
        self.waveLengthBox = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.waveLengthBox.setMinimumSize(QtCore.QSize(62, 0))
        self.waveLengthBox.setDecimals(1)
        self.waveLengthBox.setMinimum(26.5)
        self.waveLengthBox.setMaximum(30.0)
        self.waveLengthBox.setSingleStep(0.1)
        self.waveLengthBox.setProperty("value", 28.0)
        self.waveLengthBox.setObjectName("waveLengthBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.waveLengthBox)
        self.labelAmplitude = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelAmplitude.setObjectName("labelAmplitude")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelAmplitude)
        self.amplitudeBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.amplitudeBox.setMinimumSize(QtCore.QSize(62, 0))
        self.amplitudeBox.setMaximum(31)
        self.amplitudeBox.setProperty("value", 5)
        self.amplitudeBox.setObjectName("amplitudeBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.amplitudeBox)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 140, 171, 21))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButtonRx = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioButtonRx.setObjectName("radioButtonRx")
        self.horizontalLayout_2.addWidget(self.radioButtonRx)
        self.radioButtonTx = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioButtonTx.setChecked(True)
        self.radioButtonTx.setObjectName("radioButtonTx")
        self.horizontalLayout_2.addWidget(self.radioButtonTx)
        self.beamDefButton = QtWidgets.QPushButton(self.groupBox)
        self.beamDefButton.setGeometry(QtCore.QRect(10, 170, 281, 23))
        self.beamDefButton.setFlat(False)
        self.beamDefButton.setObjectName("beamDefButton")
        self.verticalLayout_2.addWidget(self.groupBox)
        self.txRxModeBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.txRxModeBox.setMaximumSize(QtCore.QSize(16777215, 40))
        self.txRxModeBox.setFlat(True)
        self.txRxModeBox.setObjectName("txRxModeBox")
        self.curSettingsLabel = QtWidgets.QLabel(self.txRxModeBox)
        self.curSettingsLabel.setEnabled(False)
        self.curSettingsLabel.setGeometry(QtCore.QRect(10, 20, 271, 20))
        self.curSettingsLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.curSettingsLabel.setObjectName("curSettingsLabel")
        self.verticalLayout_2.addWidget(self.txRxModeBox)
        self.programButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.programButton.setEnabled(False)
        self.programButton.setMinimumSize(QtCore.QSize(0, 50))
        self.programButton.setObjectName("programButton")
        self.verticalLayout_2.addWidget(self.programButton)
        self.spiStatusLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.spiStatusLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.spiStatusLabel.setStyleSheet("QLabel {color : red; }")
        self.spiStatusLabel.setTextFormat(QtCore.Qt.AutoText)
        self.spiStatusLabel.setObjectName("spiStatusLabel")
        self.verticalLayout_2.addWidget(self.spiStatusLabel)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "AWMF-0108 Demo Kit"))
        self.groubBoxAntenna.setTitle(_translate("Dialog", "Antenna Layout"))
        self.radio4x1Button.setText(_translate("Dialog", "4x1"))
        self.radio2x2Button.setText(_translate("Dialog", "2x2"))
        self.groupBox.setTitle(_translate("Dialog", "Beam Parameters"))
        self.labelTheta.setText(_translate("Dialog", "theta"))
        self.thetaBox.setSuffix(_translate("Dialog", " degrees"))
        self.labelPhi.setText(_translate("Dialog", "phi"))
        self.phiBox.setSuffix(_translate("Dialog", " degrees"))
        self.labelWavelength.setToolTip(_translate("Dialog", "Central wavelength of input signal"))
        self.labelWavelength.setText(_translate("Dialog", "wavelength"))
        self.waveLengthBox.setToolTip(_translate("Dialog", "Central wavelength of common port signal"))
        self.waveLengthBox.setSuffix(_translate("Dialog", " GHz"))
        self.labelAmplitude.setToolTip(_translate("Dialog", "Amplification of active path channels- unused lines will be set to maximum attenuation"))
        self.labelAmplitude.setText(_translate("Dialog", "amplification"))
        self.amplitudeBox.setToolTip(_translate("Dialog", "Amplification of active path channels- unused lines will be set to maximum attenuation"))
        self.amplitudeBox.setSuffix(_translate("Dialog", " dB"))
        self.radioButtonRx.setText(_translate("Dialog", "Receive"))
        self.radioButtonTx.setText(_translate("Dialog", "Transmit"))
        self.beamDefButton.setToolTip(_translate("Dialog", "Lock-in beam parameters"))
        self.beamDefButton.setText(_translate("Dialog", "Hold"))
        self.txRxModeBox.setTitle(_translate("Dialog", "Held Beam Parameters"))
        self.curSettingsLabel.setText(_translate("Dialog", "(0,0, TX)"))
        self.programButton.setToolTip(_translate("Dialog", "Sends held parameters to device"))
        self.programButton.setText(_translate("Dialog", "Program"))
        self.spiStatusLabel.setToolTip(_translate("Dialog", "Please connect a NI USB-8452 SPI interface to the computer. If one is already connected, try restarting BeamDemo"))
        self.spiStatusLabel.setText(_translate("Dialog", "SPI Interposer not detected "))

from qantennaviewer import QAntennaViewer
