# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maingui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(873, 572)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("DemoLogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 871, 571))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.glViewer = QAntennaViewer(self.horizontalLayoutWidget)
        self.glViewer.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glViewer.sizePolicy().hasHeightForWidth())
        self.glViewer.setSizePolicy(sizePolicy)
        self.glViewer.setMinimumSize(QtCore.QSize(100, 100))
        self.glViewer.setMaximumSize(QtCore.QSize(900, 900))
        self.glViewer.setSizeIncrement(QtCore.QSize(1, 1))
        self.glViewer.setObjectName("glViewer")
        self.horizontalLayout.addWidget(self.glViewer)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.logoDisplay = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logoDisplay.sizePolicy().hasHeightForWidth())
        self.logoDisplay.setSizePolicy(sizePolicy)
        self.logoDisplay.setMaximumSize(QtCore.QSize(16777215, 111))
        self.logoDisplay.setText("")
        self.logoDisplay.setPixmap(QtGui.QPixmap("anokiwave_logo.png"))
        self.logoDisplay.setObjectName("logoDisplay")
        self.verticalLayout_2.addWidget(self.logoDisplay)
        self.groupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox.setMinimumSize(QtCore.QSize(200, 130))
        self.groupBox.setMaximumSize(QtCore.QSize(2000, 140))
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 161, 81))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.labelTheta = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelTheta.setObjectName("labelTheta")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelTheta)
        self.theta = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.theta.setMinimum(-360.0)
        self.theta.setMaximum(360.0)
        self.theta.setSingleStep(0.5)
        self.theta.setObjectName("theta")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.theta)
        self.labelPhi = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelPhi.setObjectName("labelPhi")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelPhi)
        self.phi = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.phi.setMinimum(-360.0)
        self.phi.setMaximum(360.0)
        self.phi.setSingleStep(0.5)
        self.phi.setObjectName("phi")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.phi)
        self.labelWavelength = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelWavelength.setObjectName("labelWavelength")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelWavelength)
        self.waveLength = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.waveLength.setMinimumSize(QtCore.QSize(62, 0))
        self.waveLength.setMinimum(26.5)
        self.waveLength.setMaximum(30.0)
        self.waveLength.setSingleStep(0.1)
        self.waveLength.setObjectName("waveLength")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.waveLength)
        self.BeamDef = QtWidgets.QPushButton(self.groupBox)
        self.BeamDef.setGeometry(QtCore.QRect(10, 110, 161, 23))
        self.BeamDef.setObjectName("BeamDef")
        self.verticalLayout_2.addWidget(self.groupBox)
        self.txRxModeBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.txRxModeBox.setMaximumSize(QtCore.QSize(16777215, 40))
        self.txRxModeBox.setFlat(True)
        self.txRxModeBox.setObjectName("txRxModeBox")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.txRxModeBox)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 291, 21))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_2.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_2.addWidget(self.radioButton_2)
        self.verticalLayout_2.addWidget(self.txRxModeBox)
        self.programButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.programButton.setMinimumSize(QtCore.QSize(0, 50))
        self.programButton.setObjectName("programButton")
        self.verticalLayout_2.addWidget(self.programButton)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "AWMF-0108 Demo Kit"))
        self.groupBox.setTitle(_translate("Dialog", "Beam Direction"))
        self.labelTheta.setText(_translate("Dialog", "theta"))
        self.labelPhi.setText(_translate("Dialog", "phi"))
        self.labelWavelength.setText(_translate("Dialog", "wavelength"))
        self.BeamDef.setText(_translate("Dialog", "BeamDef"))
        self.txRxModeBox.setTitle(_translate("Dialog", "Transmit/Receive Mode"))
        self.radioButton.setText(_translate("Dialog", "Transmit"))
        self.radioButton_2.setText(_translate("Dialog", "Receive"))
        self.programButton.setText(_translate("Dialog", "Send it"))

from qantennaviewer import QAntennaViewer
